Update cli.py
I think incorporating %% instructs Python to interpret the sequence as a literal % character, rather than introducing a string format specifier. Without proper escaping, executing the commands 'stamp' and 'stamp --help' trigger an error due to Python misinterpreting %C as an invalid format specifier, leading to:

ValueError: unsupported format character 'C' (0x43) at index 35